### ISSUE TITLE
パソコンのセットアップ

### ISSUE THREAD

**Issue by pyohei** [monokies/bibtaro#16]
困ったことがあったら書いていってください。

**Comment by ghost** [comment]
みなさんセキュリティソフトって何か入れられてますか？
Macは入れなくても何か起こる確率は低いとは読んだのですが・・・

**Comment by pyohei** [comment]
僕はいれてないです...
（いれないとなーって思いつつ入れていない ><..）

**Comment by pyohei** [comment]
iAntiVirus を一応使っていたけど、、もう配信自体終了していた。。

Appleのサイトをみると、Macのセキュリティはすごいぞって書いている(笑)
http://www.apple.com/jp/macos/security/

**Comment by ghost** [comment]
私も入れてないです(^^;
入れようとセキュリティソフト比較とか見てるうちに面倒になって…笑

**Comment by ghost** [comment]
私も色々見てるうちに何が良いかわからなくなりました笑　
でも入れなくても大丈夫そうですね・・！ありがとうございます！

**Comment by pyohei** [comment]
おわり
